
services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-dev
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - NODE_ENV=development
      - N8N_SECURE_COOKIE=false
      - N8N_USER_EMAIL=admin@example.com
      - N8N_USER_PASSWORD=supersecret
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - DB_SQLITE_POOL_SIZE=5
      - N8N_RUNNERS_ENABLED=true
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - ATTACHMENT_API_KEY=${ATTACHMENT_API_KEY}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./dist:/home/node/.n8n/custom/node_modules/@widdix/attachmentav-n8n
      - ./testWorkflows:/tmp/workflows:ro
      - ./docker-entrypoint.sh:/docker-entrypoint.sh:ro
    entrypoint: ["/bin/sh", "/docker-entrypoint.sh"]

volumes:
  n8n_data:
